### ISSUE TITLE
Prozessing files bigger than 10MB lead to: thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#117] opened 2017-12-25 19:54 UTC
Processing a file above 10MB with following comand:
>$ svgcleaner [Stations_Vélhop.svg](https://commons.wikimedia.org/wiki/File:Stations_V%C3%A9lhop.svg) output.svg

lead to an error:
`
thread 'main' has overflowed its stack
`

**Comment by RazrFalcon** [comment] 2017-12-25 21:05
It's actually the svgdom bug and I have no idea how to fix it. Will try to find a solution.

**Comment by RazrFalcon** [comment] 2017-12-25 21:19
Also, it crashes only in the debug mode.

**Comment by JoKalliauer** [comment] 2017-12-26 08:54
The strange thing is that svgcleaner reduced the file size, and it has all closing tags, it ends with `</g></svg>`, and it is valid file and it looks like the original file (30MB), therefore I'm not shure if it really crashes.

**Comment by RazrFalcon** [comment] 2017-12-26 09:17
The problem is that it crashes during the DOM destructing, after file being processed.

**Comment by RazrFalcon** [comment] 2018-01-17 16:55
Basically, I have to rewrite [svgdom](https://github.com/RazrFalcon/libsvgdom) which is will not happen anytime soon.

**Comment by JoKalliauer** [comment] 2018-01-28 22:36
You maybe already know it:
I noticed that not the filesize it is the number of tags.
I get problems with a file which has 10.000 path-tags but is less than 300kB, but I don't get any problems with a file using a single path-tag, but bigger than 10MB.

I tried Processing:
[https://commons.wikimedia.org/wiki/File:1_42_polytope_7-cube.svg](https://commons.wikimedia.org/wiki/File:1_42_polytope_7-cube.svg)
once before merging 480.000paths (using [svgo](https://github.com/svg/svgo)) and once afterwards, afterwards I didn't had any problems.

Actually a function `merging path` would also be a nice feature. (Merging more than 10.000Path is very slow in [svgo](https://github.com/svg/svgo), and svgo is generally more buggy than your script.)

But if it is too complex, it's maybe not worth it.

**Comment by RazrFalcon** [comment] 2018-01-29 10:25
I hope this bug will be fixed soon. The current algorithm is incorrect. And yes, this bug occurs because of many nested nodes. File size doesn't matter.

Paths merging isn't that hard, but I don't have time to do this now.

**Comment by RazrFalcon** [comment] 2018-01-29 16:00
Should be fixed now. Just rebuild stable `svgcleaner`. It will be build with the latest `svgdom` (v0.10.3) which has corresponding fixes.

**Closed by RazrFalcon** 2018-01-29 16:00 UTC
Labels: Bug, Complex
