### ISSUE TITLE
Missing color in path with latest

### ISSUE THREAD

**Issue by stoecker** [RazrFalcon/SVGCleaner#31] opened 2016-07-17 12:12 UTC
In our tools JOSM we use svgcleaner permanently to reduce file sizes. After an server upgrading (and switch to latest source) we detected an error in one cleaning operation. See https://josm.openstreetmap.de/ticket/13158 for more details.

Essentially a color information is missing in the newest versions path element.

**Comment by stoecker** [comment] 2016-07-17 12:16
I tried to add the files here as well, but failed. Please take them from our bug report. It contains the original (notary.png), the working version for 0.6.2 (notary_10504.png), the failing latest (notary_10505.png) and the fixed latest (notary_10505_fixed.png). The cleaned ones with additional carriage returns for better visibility.

**Comment by RazrFalcon** [comment] 2016-07-17 12:31
Hello. Your link returns 404 error.

By "newest versions" you mean from master and not by tag?

**Comment by stoecker** [comment] 2016-07-17 12:59
Fixed the link to point at what it says :-)

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="m0 0v16h16v-16z" style="color:#000000;-inkscape-font-specification:Sans;fill:#3771c8"/></svg>
`

I searched the cause a bit deeper and have above minimal example. It seems the "-inkscape-font-specification" is the cause. If I remove that it works.

Yes. Newest means master.

**Comment by RazrFalcon** [comment] 2016-07-17 13:08
Yes. That's it. SVG Cleaner always extracts style attributes, but attributes name must starts with an a-zA-Z, not '-'. I don't know why Inkscape uses incorrect(kinda) format.

The problem is that parser stops after incorrect attribute name and all data after ignored. It's fixed long ago in private/devel branch, but i don't know when it will be released.

**Comment by bastik** [comment] 2016-07-17 16:13
Property names starting with a dash are not uncommon and are even mentioned in the specification:
https://www.w3.org/TR/CSS21/syndata.html#vendor-keywords

**Comment by RazrFalcon** [comment] 2016-07-17 16:21
It's CSS. SVG Cleaner does not support them, mostly. Also SVG Cleaner does not support 'style' attribute, so it should be split into attributes. And here we have a bug, that can be 'fixed' only by skipping unknown attributes. So it's mostly a design flaw of SVG Cleaner DOM.

**Comment by RazrFalcon** [comment] 2016-08-26 15:02
Fixed.

**Closed by RazrFalcon** 2016-08-26 15:02 UTC
