### ISSUE TITLE
Improvement merge text and tspan

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#127] opened 2018-01-13 23:46 UTC
I would like to merge simple `<text>` with `<tspan>`

Inputexample:
```svg
 <text x="313.88" y="322.89">
  <tspan x="313.88" y="322.89">1</tspan>
 </text>
```
Output:
```svg
 <text x="313.88" y="322.89">1</text>
```

actually I am using (case-depended) following scripts:
```bash
#tspan in tspan
sed -ri -e ':a' -e 'N' -e '$!ba' -e "s/<tspan([-[:alnum:]\,\.\"\=\:\ \#]*) x=\"([-[:digit:]\.\ ]+)\" y=\"([-[:digit:]\.\ ]+)\"([-[:alnum:]\,\.\"\=\:\ \#]*)>[[:space:]]*<tspan([-[:alnum:]\,\.\"\=\:\ \#]*) x=\"([-[:digit:]\.\ ]+)\" y=\"([-[:digit:]\.\ ]+)\"([-[:alnum:]\,\.\"\=\:\ \#]*)>([-[:alnum:]\.\ \,\(\)]*)<\/tspan>/<tspan x=\"\6\" y=\"\7\"\1\4\5\8>\9/g" $i
```
```bash
#tspan to text
sed -ri  -e ':a' -e 'N' -e '$!ba' -e "s/<text([-aeflmnorst0-9\,\.\"\=\:\ \#\(\)]*)( x=\"[-[:digit:]\.\ ]+\" y=\"[-[:digit:]\.\ ]+\")/<text\2\1/g" $i # that x ist at the beginning (otherwise the next line would not work)
sed -ri  -e ':a' -e 'N' -e '$!ba' -e "s/<text( x=\"[-[:digit:]\.\ ]+\" y=\"[-[:digit:]\.\ ]+\"|)([-[:alnum:]\,\.\"\=\:\ \#\(\)\%\']*)>[[:space:]]*<tspan([-[:alnum:]\,\.\"\=\:\ \#]*) x=\"([-[:digit:]\.\ ]+)\" y=\"([-[:digit:]\.\ ]+)\"([-[:alnum:]\,\.\"\=\:\ #]*)>([-–[:alnum:]\.\ \,\{\(\)\♭\♯\/]*)<\/tspan>/<text x=\"\4\" y=\"\5\"\2\3\6>\7/g" $i #removes the first tspan of a text element
```
```bash
#tspan to text if tspan has no coordinates
sed -ri  -e ':a' -e 'N' -e '$!ba' -e "s/<text([-[:alnum:]\,\.\"\=\:\ \#\(\)]*) x=\"([-[:digit:]\.\ ]+)\" y=\"([-[:digit:]\.\ ]+)\"([-[:alnum:]\,\.\"\=\:\ \#\(\)\%\']*)>[[:space:]]*<tspan([-[:alnum:]\,\.\"\=\:\ \#\'\%]*)>([-–[:alnum:]\.\ \,\{\(\)]*)<\/tspan>/<text x=\"\2\" y=\"\3\"\1\4\5>\6/g" $i
```
it works in most cases but they can be buggy.

If you are interested to implement it I can post some more general testexamples.

**Comment by RazrFalcon** [comment] 2018-01-14 08:22
There is nothing to improve because it's not implemented at all.

Also, your example is too simple. Actual text and tspan are far more complex.

This will be implemented some day.

**Comment by RazrFalcon** [comment] 2018-01-17 16:50
Duplicate of https://github.com/RazrFalcon/svgcleaner/issues/39

**Closed by RazrFalcon** 2018-01-17 16:50 UTC
Labels: Improvement
